/*
 * This source file was generated by the Gradle 'init' task
 */
package org.day6

import java.io.File

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun applyOp(op: String, vararg nums: String): Long {
    val result = when (op) {
        "+" -> nums.sumOf { it.toLong() }
        "*" -> nums.map { it.toLong() }.fold(1L) { acc, num -> acc * num }
        else -> throw Exception("Shouldn't happen")
    }
    println("op: $op args: ${nums.joinToString(", ")} - result: $result")

    return result
}

fun main() {
    val lines = File("data/input.txt").readLines()
    val splitLines = lines.map { it.trim().split("\\s+".toRegex()) }
    var sum: Long = 0
    for (i in 0..<splitLines[0].size) {
        sum += applyOp(splitLines[4][i], splitLines[0][i], splitLines[1][i], splitLines[2][i], splitLines[3][i])
    }
    println(sum)
}
