/*
 * This source file was generated by the Gradle 'init' task
 */
package org.day6

import java.io.File

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun applyOp(op: String, nums: List<Long>): Long {
    val result = when (op) {
        "+" -> nums.sum()
        "*" -> nums.fold(1L) { acc, num -> acc * num }
        else -> throw Exception("Shouldn't happen")
    }

    return result
}

fun parseNum(vararg digits: Char): Long{
    return digits.fold("") { acc, digit ->
        when (digit) {
            ' ' -> acc
            else -> acc+digit
        }
    }.toLong()
}

fun main() {
    val lines = File("data/input.txt").readLines()
    val endIndex = lines[0].length-1

    var sum: Long = 0

    val nums = mutableListOf<Long>()
    var op: String? = null
    for (i in 0..endIndex) run {

        val col = lines.map {it[i]}
        if (col[4] != ' '){
            op = col[4].toString()
        }
        if (col.any {it != ' '}){
            nums.add(parseNum(col[0], col[1], col[2], col[3]))
        }
        if (col.all {it == ' ' || i == endIndex}){
            println("op: $op args: ${nums.joinToString(", ")}")
            sum += applyOp(op.toString(), nums)
            nums.clear()
            op = null
        }
    }
    println(sum)
}
